server:
  port: 8085
spring:
  application:
    name: Config-Server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8585/eureka
    fetch-registry: true
    register-with-eureka: true
